---
title: "R Notebook"
output: document_md
---

```{r}
rm(list = ls()) ; gc()

library(data.table)
library(magrittr)
library(ggplot2)
library(pbapply)
library(parallel)
library(patchwork)
library(future)

source("./R/utils.R")
```


# Read M4 data and inspect frequencies
```{r}
plan(cluster, workers = 1)

f <- future(source("./Cache/Article_M4_Comparison.R"),
            globals = "calculate_khs_feats")

resolved(f)
value(f)
```

# Calculate KHS features with and without seasonality
```{r}
rstudioapi::
```

# Visualizing M4 with and without seasonality for Daily and Weekly Series

```{r}


# Construtc plotting functions
minimal_autoplot <- function(object, colour = NULL, scale = 1, x = 1, y = 2, variance_percentage = TRUE,
                             loadings = FALSE, loadings.label = FALSE, loadings.label.repel = FALSE) {
  require(ggfortify)
  plot.data <- ggfortify:::fortify.prcomp(object)
  plot.data$rownames <- rownames(plot.data)
  
  if(!is.null(colour)) {
    stopifnot(length(colour) == nrow(plot.data))
    plot.data$colour <- colour
  } 
  
  ve <- object$sdev^2/sum(object$sdev^2)
  PC <- paste0("PC", c(x, y))
  x.column <- PC[1]
  y.column <- PC[2]
  loadings.column <- "rotation"
  lam <- object$sdev[c(x, y)]
  lam <- lam * sqrt(nrow(plot.data))
  
  if (scale != 0) {
    lam <- lam^scale
    plot.data[, c(x.column, y.column)] <- t(t(plot.data[, 
                                                        c(x.column, y.column)])/lam)
  }
  
  plot.columns <- unique(c(x.column, y.column, colnames(plot.data)))
  plot.data <- plot.data[, plot.columns]
  if (!is.null(loadings.column)) {
    loadings.data <- as.data.frame(object[[loadings.column]][, 
                                                             ])
    loadings.data$rownames <- rownames(loadings.data)
    loadings.columns <- unique(c(x.column, y.column, colnames(loadings.data)))
    loadings.data <- loadings.data[, loadings.columns]
  }
  
  ve <- ve[c(x, y)]
  labs <- paste0(PC, " (", round(ve * 100, 2), "%)")
  
  xlab <- labs[1]
  ylab <- labs[2]
  if(!is.null(colour)) {
    p <- ggfortify::ggbiplot(plot.data = plot.data, loadings.data = loadings.data, 
                             xlab = xlab, ylab = ylab, colour = "colour", loadings = loadings, loadings.label = loadings.label, 
                             loadings.label.repel = loadings.label.repel)
  } else {
    p <- ggfortify::ggbiplot(plot.data = plot.data, loadings.data = loadings.data, 
                             xlab = xlab, ylab = ylab, loadings = loadings, loadings.label = loadings.label, 
                             loadings.label.repel = loadings.label.repel)
  }
  
  p
}


plot_M4_feats <- function(x, title = "") {
  x[, -c("N", "Frequency", "Period")] %>%
    prcomp(scale = T) %>%
    minimal_autoplot(colour = factor(M4$period, levels = c("Hourly", "Daily", "Weekly", "Monthly", "Quarterly", "Yearly"))) +
    # Trend and ACF 1 Arrow & Text
    geom_segment(aes(x = -0.010, xend = 0.000, y = 0.006, yend = 0.006),
                 lineend = "round", linejoin = "round", arrow = arrow(type = "closed")) +
    geom_text(aes(x = -0.005, y = 0.007, label = "Trend & ACF1")) +
    # Lambda and Season Arrow & Text
    geom_segment(aes(x = 0.005, xend = 0.005, y = 0.0025, yend = -0.005),
                 lineend = "round", linejoin = "round", arrow = arrow(type = "closed")) +
    geom_text(aes(x = 0.006, y = -0.00125, label = "Lambda & Season"), angle = 270) +
    # Entropy Arrow & Text
    geom_segment(aes(x = 0.000, xend = -0.010, y = -0.0101, yend = -0.0101),
                 lineend = "round", linejoin = "round", arrow = arrow(type = "closed")) +
    geom_text(aes(x = -0.005, y = -0.0105, label = "Entropy")) +
    theme_bw(base_family = "serif") +
    ggtitle(title)
}

# Construct Feature plots for M4 
M4_adjusted_plot <- plot_M4_feats(M4_adjusted_feats, "Adjusted Frequency")
M4_original_plot <- plot_M4_feats(M4_original_feats, "Original Frequency")

# Assemble Patchwork with plots
M4_frequency_plot <- M4_original_plot + M4_adjusted_plot +
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom", 
        plot.title = element_text(hjust = 0.5),
        axis.ticks = element_blank(),
        axis.text = element_blank()) &
  guides(color = guide_legend("Period"))


plan(cluster, workers = 1)
f <- futureCall(
  ggsave,
  args = list(
    filename = "./Figures/article/M4_frequency_comparison.png",
    plot = M4_frequency_plot
  )
)

resolved(f)

```


```{r}
get_decimals <- function(x) attr(regexpr("(?<=\\.)0+|$", x, perl = TRUE), "match.length")


vertical_arrow <- loadings.data[abs(0 - loadings.data[, c(x.column)]) < abs(0 - loadings.data[, c(y.column)]), ]
vertical_arrow_top_to_bot <- vertical_arrow[vertical_arrow[, c(y.column)] < 0, ]
vertical_arrow_bot_to_top <- vertical_arrow[vertical_arrow[, c(y.column)] > 0, ]

horizontal_arrow <- loadings.data[!loadings.data$rownames %in% vertical_arrow$rownames, ]
horizontal_arrow_right_to_left <- horizontal_arrow[horizontal_arrow[, c(x.column)] < 0, ]
horizontal_arrow_left_to_right <- horizontal_arrow[horizontal_arrow[, c(x.column)] > 0, ]

x_max <- max(plot.data[, c(x.column)])
x_min <- min(plot.data[, c(x.column)])
y_max <- max(plot.data[, c(y.column)])
y_min <- min(plot.data[, c(y.column)])
x_max_dec <- get_decimals(x_max)
x_min_dec <- get_decimals(x_min)
y_max_dec <- get_decimals(y_max)
y_min_dec <- get_decimals(y_min)

if(x_max < 0) {
  rx_max <- x_max - as.numeric(paste0("0.", paste(as.character(rep(0, x_max_dec)), collapse = ""), "05"))
} else {
  rx_max <- x_max + as.numeric(paste0("0.", paste(as.character(rep(0, x_max_dec)), collapse = ""), "05"))
}

if(x_min < 0) {
  rx_min <- x_min - as.numeric(paste0("0.", paste(as.character(rep(0, x_min_dec)), collapse = ""), "05"))
} else {
  rx_min <- x_min + as.numeric(paste0("0.", paste(as.character(rep(0, x_min_dec)), collapse = ""), "05"))
}

if(y_max < 0) {
  ry_max <- y_max + as.numeric(paste0("0.", paste(as.character(rep(0, y_max_dec)), collapse = ""), "05"))
} else {
  ry_max <- y_max + as.numeric(paste0("0.", paste(as.character(rep(0, y_max_dec)), collapse = ""), "05"))
}

if(y_min < 0) {
  ry_min <- y_min + as.numeric(paste0("0.", paste(as.character(rep(0, y_min_dec)), collapse = ""), "05"))
} else {
  ry_min <- y_min + as.numeric(paste0("0.", paste(as.character(rep(0, y_min_dec)), collapse = ""), "05"))
}


p + geom_segment(aes(x = rx_min, xend = rx_max, y = t, yend = t),
                 arrow = grid::arrow(length = grid::unit(8, "points"), type = "closed"))

ggplot() + geom_segment(aes(x = rx_min, xend = rx_max, y = ry_max, yend = ry_max),
                        arrow = grid::arrow(length = grid::unit(8, "points"), type = "closed")) +
  geom_text(aes(x = -((rx_max + abs(rx_min)) / 2), y = ry_max, label = "hat"), nudge_y = as.numeric(get_dec(ry_max)))


```

