---
title: "R Notebook"
output: document_md
---

# Initilization

```{r, message=FALSE, warning=FALSE}
## Clear Environment & Load Packages
rm(list = ls()) ; gc()
library(tidyverse)
library(lubridate)
library(data.table)
library(tsibble)
library(tsfeatures)
library(furrr)
library(ggfortify)

## Source Functions
source("R/utils.R")
source("R/prepdata.R")
source("R/svd.R")

## Open / Close multiprocess is quite expensive.... Therefore we open it once in top.
## Plan Multiprocess for Parallel Processing... NOTE Remains open until plan(sequential) is executed
plan(multiprocess)
```

# Walmart
```{r}
walmart_data <- readRDS("../Data/walmart-recruiting-store-sales-forecasting/combined.Rds")

walmart_data <- future_map(walmart_data, prepdata, target = "weekly_sales", date = "date", group = c("store", "dept", "type"))
wm_train <- walmart_data$train
wm_test<- walmart_data$test
feats <- walmart_data$features
stores <- walmart_data$stores
```

## Investigate Time Series Characteristics
```{r, fig.width=15, fig.height=12}
wm_train[, 
         .(n = as.double(.N),
           non_zero = as.double(sum(weekly_sales > 0)),
           pct_non_zero = as.double(sum(weekly_sales > 0)/.N),
           num_seas = as.double(52/.N)), 
         .(store, dept)] %>%
  melt(id.vars = c("store", "dept")) %>%
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~variable, scales = "free")
```

## Investigate Time Series Features
```{r, warning = FALSE, message=FALSE}
tictoc::tic("Collect Time Series Features")
tsib <- wm_train[, .(data = list(.SD)), .(store, dept)]
tsib[, ts := map(data, ~forecast::msts(.$weekly_sales, seasonal.periods = c(round(365.25/7, 2), 365.25), start = decimal_date(min(.$date))))]
tsib[, feats := future_map(ts, possibly(tsfeats, NA), scale = F, features = c("stl_features", "entropy"))]
tsib[, check := sapply(feats, is.logical)]
wm_feats <- tsib[check == FALSE, unlist(feats, recursive = F), .(store, dept)]
tictoc::toc()
```


```{r, warning=FALSE, fig.width=15, fig.height=12}
pcs <- wm_feats %>%
  select(-store, -dept) %>%
  mutate_all(~replace_na(.x, replace = mean(.x, na.rm = TRUE))) %>%
  prcomp(scale=TRUE)

autoplot(pcs, loadings = TRUE, loadings.label = TRUE)
```

```{r, fig.width=15, fig.height=12}
setDT(wm_feats)[, .(store, dept, seasonal_strength, trend, entropy)] %>%
  melt(id.vars = c("store", "dept")) %>%
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~variable)
```

## Investigate Additional Features
```{r}
# Stores
unique(wm_train[, .(store, dept)]) %>%
  .[stores, on = "store"] %>%
  .[, .(n_distinct = uniqueN(store), .N), .(dept, type)]
```

```{r, warning = FALSE, fig.width=15, fig.height=12}
# Holiday Correlation
wm_train[, .(cor = cor(weekly_sales, is_holiday, method = "spearman", use = "na.or.complete")), .(store, dept)] %>%
  .[, .(cor, mean_cor = mean(abs(cor), na.rm = T))] %>%
  ggplot(aes(x = cor)) + geom_histogram() + geom_vline(aes(xintercept = mean_cor))
```

```{r, warning = FALSE}
# Additional Features
train_w_var <- wm_train %>%
  left_join(feats %>% select(-is_holiday) %>% mutate(date = yearweek(date)), by = c("store", "date"))

setDT(train_w_var)
feat_cols <- names(train_w_var[, !c("store", "dept", "date")])
train_w_var[is.na(train_w_var)] <- 0

tictoc::tic("Feature Correlation")
cor_df <- train_w_var[, .(data = list(.SD)), .(store, dept), .SDcols = feat_cols] %>%
  .[, cor := future_map(data, get_correlations, target = "weekly_sales")]
tictoc::toc() # Time Elapsed: 16.03 sec elapsed
```


```{r, warning=FALSE, fig.width=15, fig.height=12}
cor_df[, unlist(cor, recursive = F), .(store, dept)] %>%
  .[, .(cor, mean_cor = mean(abs(cor), na.rm = T)), variable] %>%
  ggplot(aes(x = cor)) + geom_histogram() + geom_vline(aes(xintercept = mean_cor)) + facet_grid(~variable)
```

```{r}
overall_cor <- get_correlations(train_w_var[, !c("store", "dept", "date")], target = "weekly_sales") %>%
  arrange(desc(abs(cor)))

overall_cor
```

## Investigate Seasonality
```{r, fig.width=15, fig.height=12}
wm_train[dept %in% 1:10, .(doy = yday(date), year = year(date), weekly_sales, store, dept)] %>%
  ggplot(aes(x = doy, y = weekly_sales, group = store)) + 
  geom_line(alpha = .5) + 
  facet_grid(year~dept)
```

## Single-value Decomposition
```{r, fig.width=15, fig.height=12}
wm_svd <- wm_train[, .(data = list(.SD)), .(dept)]
wm_svd <- wm_svd[, cast := lapply(data, dcast, date+is_holiday~store, value.var = "weekly_sales", fill = 0)]
wm_svd[, matrix := lapply(cast, function(x) makeMatrixWithNAZero(x[,!c("date", "is_holiday")]))]
wm_svd[, svd := future_map2(matrix, cast, possibly(truncated_svd, NA))]
wm_svd[, check := sapply(svd, is.data.table)]
wm_svd <- wm_svd[check != FALSE, ]
wm_svd[, ex_var := future_map2(data, svd, calculate_svd_errors)]
svd_result <- wm_svd[, unlist(ex_var, recursive = F), dept]

svd_result %>%
  ggplot(aes(x = comp, y = var_exp, group = dept)) + 
  geom_line() + 
  scale_y_continuous(limits = seq(0, 1)) + 
  facet_wrap(~dept)
```
