---
title: "R Notebook"
output: document_md
---

# Initilization
```{r, message=FALSE, warning=FALSE}
## Clear Environment & Load Packages
rm(list = ls()) ; gc()
library(magrittr)
library(lubridate)
library(data.table)
library(tsfeatures)
library(purrr)
library(furrr)
library(ggfortify)
library(tidyverse)
library(forecast)

## Source Functions
source("R/utils.R")
source("R/prepdata.R")
source("R/svd.R")

## Open / Close multiprocess is quite expensive.... Therefore we open it once in top.
## Plan Multiprocess for Parallel Processing... NOTE Remains open until plan(sequential) is executed
plan(multiprocess)
```


# Rossmann
```{r}
path <- "../Data/rossmann-store-sales/combined.Rds"

target <- "sales"
group <- "store"
index <- "date"
ts_frequency <- c(365.25)
commonality <- "store_type"

raw_data <- readRDS(path)
raw_data <- future_map(raw_data, prepdata, group = group, index = index, target = target, fill_target = 0, fill_dates = TRUE)

train <- as_dtts(raw_data$train, group = group, target = target, index = index, "train")
train_feats <- as_dtts(raw_data$train, group = group, target = target, index = index, "features")
additional_feats <- raw_data$store
test <- raw_data$test

# Fix NA's caused by filling dates
train[is.na(train)] <- 0
train_feats[is.na(train_feats)] <- 0

# Set Key and Index
setkeyv(train, group)
setindexv(train, index)

# Remove raw data
rm(raw_data) ; gc()
```



```{r}
ts_summary(train, target = target, group = group, frequency = ts_frequency)$plot
```




```{r}
tictoc::tic("Collect Time Series Features")
khs_feats <- khs_ts_features(.data = train,
                             target = target,
                             group = group,
                             index = index,
                             frequency = ts_frequency,
                             parallel = T)
tictoc::toc()
```


```{r}
tictoc::tic("Collect Time Series Features")
rs_feats <- ts_features(.data = rs_train, 
                        target = target, 
                        group = group, 
                        date_col = index,
                        frequency = ts_frequency, 
                        parallel = TRUE,
                        scale = F,
                        features = c("stl_features", "entropy", "acf_features"))
tictoc::toc()
```



```{r}
pcs <- get_pcs(rs_feats, group, scale = T)

autoplot(pcs, loadings = TRUE, loadings.label = TRUE)
```



```{r}
rs_feats[, .(store, seasonal_strength, trend, entropy)] %>%
  melt(id.vars = group) %>%
  ggplot(aes(value)) + geom_histogram() + facet_wrap(~variable)
```



```{r}
# Additional Features
train_w_var <- rs_train_feats[rs_train, on = c(group, index)]
train_w_var[, state_holiday := as.integer(as.factor(state_holiday))]
feat_cols <- colnames_excluded(train_w_var, exclude = c(group, index))

tictoc::tic("Feature Correlation")
cor_df <- train_w_var[, .(data = list(.SD)), group, .SDcols = feat_cols] %>%
  .[, cor := future_map(data, get_correlations, target = target)]
tictoc::toc()
```



```{r}
cor_df[, rbindlist(cor), group] %>%
  .[, .(cor, mean_cor = mean(abs(cor), na.rm = T)), variable] %>%
  ggplot(aes(x = cor)) + geom_histogram() + geom_vline(aes(xintercept = mean_cor)) + facet_grid(~variable)
```



```{r}
overall_cor <- get_correlations(train_w_var[, !c(group, index), with = F], target = target) %>%
  .[order(-abs(cor))]

overall_cor
```



```{r}
rs_train[store %in% 1:10, .(doy = yday(date), year = year(date), sales, store)] %>%
  ggplot(aes(x = doy, y = sales, group = store)) + 
  geom_line(alpha = .5) + 
  facet_grid(year~store)
```

```{r}
rs_train[rs_store, on = group, c(commonality) := get(commonality)]

tictoc::tic("Single Value Decomposition")
rs_svd <- calculate_svd(rs_train, 
                        commonality = commonality,
                        group = group,
                        index = index,
                        target = target,
                        fill_target = 0,
                        na.rm = FALSE,
                        parallel = TRUE)
tictoc::toc()

rs_svd$svd_errors %>%
  ggplot(aes(x = comb, y = var_exp, group = get(commonality))) + 
  geom_line() + 
  facet_wrap(~get(commonality))
```

