---
title: "RossmannBM"
output: html_document
---

# Rossmann
```{r}
library(data.table)
library(forecast)
library(tsibble)
library(tidyverse)
library(lubridate)
library(zoo)

train <- fread("~/kaggle/rossmann/train.csv") %>% mutate(Date = ymd(Date))
test <- fread("~/kaggle/rossmann/test.csv") %>% mutate(Date = ymd(Date))
```

## Naive
```{r}
naive <- train %>% group_by(Store) %>% top_n(n = 1, wt = Date) %>% select(Store, Sales)

test %>%
  left_join(naive, by = c("Store")) %>%
  mutate(
    Open = replace_na(Open, 1L),
    Sales = if_else(Open == 0, 0L, Sales)
  ) %>%
  select(Id, Sales) %>% 
  write.csv("rossmann_naive_by_store.csv", row.names = F)
```

## Seasonal Naive
```{r}
seasonal_naive <- train %>% group_by(Store, DayOfWeek) %>% top_n(n = 1, wt = Date) %>% select(Store, DayOfWeek, Sales)

test %>%
  left_join(seasonal_naive, by = c("Store", "DayOfWeek")) %>%
  mutate(
    Open = replace_na(Open, 1L),
    Sales = if_else(Open == 0, 0L, Sales)
  ) %>%
  select(Id, Sales) %>% 
  write.csv("rossmann_seasonal_naive_by_store.csv", row.names = F)
```

## Seasonal Naive Promo
```{r}
seasonal_naive_promo <- train  %>% group_by(Store, DayOfWeek, Promo) %>% top_n(n = 1, wt = Date) %>% select(Store, DayOfWeek, Promo, Sales)
test %>%
  left_join(seasonal_naive_promo, by = c("Store", "DayOfWeek", "Promo")) %>%
  mutate(
    Open = replace_na(Open, 1L),
    Sales = if_else(Open == 0, 0L, Sales)
  ) %>%
  select(Id, Sales) %>% 
  write.csv("rossmann_seasonal_naive_by_store_promo.csv", row.names = F)
```

# Walmart
```{r}
train <- fread("~/kaggle/walmart/train.csv") %>% mutate(Date = ymd(Date))
test <- fread("~/kaggle/walmart/test.csv") %>% mutate(Date = ymd(Date))
features <- fread("~/kaggle/walmart/features.csv") %>% mutate(Date = ymd(Date))

train %>% 
  left_join(features) %>% 
  select(-Date, -Store, -Dept) %>% 
  mutate_all(replace_na, replace = 0) %>% 
  gather(key = feature, value = feature_value, -Weekly_Sales) %>% 
  group_by(feature) %>% 
  summarize(
    cor = cor(Weekly_Sales, feature_value, method = "spearman")
  )
```

## Naive
```{r}
naive <- train %>% group_by(Store, Dept) %>% top_n(n = 1, wt = Date) %>% select(Store, Dept, Weekly_Sales)


test %>%
  left_join(naive, by = c("Store", "Dept")) %>%
  group_by(Dept) %>%
  mutate(
    Dept_mean = mean(Weekly_Sales, na.rm = TRUE),
    Weekly_Sales = if_else(is.na(Weekly_Sales), Dept_mean, Weekly_Sales),
    Id = str_c(Store, Dept, Date, sep = "_")
  ) %>%
  ungroup %>% 
  select(Id, Weekly_Sales) %>% 
  write.csv("walmart_naive_by_store_dept.csv", row.names = F)
```

## Seasonal Naive
```{r}
train %>% bind_rows(test %>% mutate(test = TRUE)) %>%
  mutate(Week = week(Date)) %>% 
  distinct(year(Date), Week, IsHoliday) %>% 
  mutate(LY = lag(Week, 52), LH = lag(IsHoliday, 52)) %>% 
  filter(!is.na(LY)) 


week_aligner <- train %>%
  bind_rows(test %>% mutate(test_set = TRUE)) %>%
  mutate(Week = week(Date)) %>% 
  distinct(year = year(Date), Week, IsHoliday, test_set) %>% 
  mutate(match_week = lag(Week, 52)) %>% 
  filter(test_set) %>% 
  select(Week, match_week)

seasonal_naive_dataset <- train %>% 
  mutate(Week = week(Date), Year = year(Date)) %>%
  filter(Year >= 2011, ! (Week < 45 & Year == 2011))

fallback_specific <- seasonal_naive_dataset %>% 
  group_by(Dept, Week) %>%  
  summarize(
    Dept_week_mean = mean(Weekly_Sales, na.rm = TRUE)
  ) %>%
  ungroup

falllback_general <- seasonal_naive_dataset %>% 
  group_by(Dept) %>%  
  summarize(
    Dept_mean = mean(Weekly_Sales, na.rm = TRUE)
  ) %>%
  ungroup 
  
seasonal_naive <- seasonal_naive_dataset %>% select(Store, Dept, Week, Year = Year, Weekly_Sales)

preds <- test %>% 
  mutate(Week = week(Date)) %>% 
  left_join(week_aligner, by = "Week") %>% 
  left_join(seasonal_naive, by = c("Store", "Dept", "match_week" = "Week")) %>%
  left_join(fallback_specific, by = c("Dept", "match_week" = "Week")) %>%
  left_join(fall_back_general, by = c("Dept")) %>%
  mutate(
    Weekly_Sales = if_else(is.na(Weekly_Sales), Dept_week_mean, Weekly_Sales),
    Weekly_Sales = if_else(is.na(Weekly_Sales), Dept_mean, Weekly_Sales),
    Id = str_c(Store, Dept, Date, sep = "_")
  ) 

preds %>% select(Id, Weekly_Sales) %>% write.csv("walmart_seasonal_naive_by_store_dept.csv", row.names = F)

```




## Choosing Fallback
We analyze whether store variance or department variance is highest to figure out which average to fall back on - it is clear that department variance is the lowest.
```{r}
train %>% group_by(Store, Dept) %>% summarize(ms = mean(Weekly_Sales)) %>% group_by(Store) %>% summarize(cov = sd(ms)/mean(ms)) %>% ggplot(aes(y = cov)) + geom_boxplot()
train %>% group_by(Dept, Store) %>% summarize(ms = mean(Weekly_Sales)) %>% group_by(Dept) %>% summarize(cov = sd(ms)/mean(ms)) %>% ggplot(aes(y = cov)) + geom_boxplot() + scale_y_continuous(limits = c(0, 2.5))

```


#Favorita
```{r}
train <- fread("~/kaggle/favorita/train.csv") %>% mutate(date = ymd(date))
test <- fread("~/kaggle/favorita/test.csv") %>% mutate(date = ymd(date))

```


## Naive
```{r}
naive <- train %>% 
  group_by(store_nbr, item_nbr) %>% 
  top_n(n = 1, wt = date)%>%
  select(store_nbr, item_nbr, unit_sales)


preds <- test %>% 
  left_join(naive, by = c("store_nbr", "item_nbr")) %>%
  group_by(item_nbr) %>% 
  mutate(
    item_mean = mean(unit_sales, na.rm = TRUE),
    unit_sales = if_else(is.na(unit_sales), item_mean, unit_sales)
  ) %>% 
  group_by(store_nbr) %>% 
  mutate(
    store_mean = mean(unit_sales, na.rm = TRUE),
    unit_sales = if_else(is.na(unit_sales), store_mean, unit_sales),
    unit_sales = if_else(unit_sales < 0, 0, unit_sales)
  ) %>%
  ungroup

preds %>% select(id, unit_sales) %>% write.csv("favorita_naive_by_store_item.csv", row.names = F)
```

## Seasonal Naive
```{r}
seasonal_naive <- train %>% 
  mutate(dow = wday(date)) %>% 
  group_by(store_nbr, item_nbr, dow) %>% 
  top_n(n = 1, wt = date) %>%
  select(store_nbr, item_nbr, dow, unit_sales)

fallback_store_item <- seasonal_naive %>% 
  group_by(store_nbr, item_nbr) %>%
  summarize(store_item_mean = mean(unit_sales, na.rm = TRUE))

fallback_item_dow <- seasonal_naive %>% 
  group_by(item_nbr, dow) %>% 
  summarize(item_dow_mean = mean(unit_sales, na.rm = TRUE))

fallback_store_dow <- seasonal_naive %>% 
  group_by(store_nbr, dow) %>% 
  summarize(store_dow_mean = mean(unit_sales, na.rm = TRUE))


seasonal_naive_preds <- test %>% 
  mutate(dow = wday(date)) %>% 
  left_join(seasonal_naive, by = c("store_nbr", "item_nbr", "dow")) %>% 
  left_join(fallback_store_item, by = c("store_nbr", "item_nbr")) %>% 
  left_join(fallback_item_dow, by = c("item_nbr", "dow")) %>% 
  left_join(fallback_store_dow, by = c("store_nbr", "dow")) %>% 
  mutate(
    unit_sales = if_else(is.na(unit_sales), store_item_mean, unit_sales),
    unit_sales = if_else(is.na(unit_sales), item_dow_mean, unit_sales),
    unit_sales = if_else(is.na(unit_sales), store_dow_mean, unit_sales),
    unit_sales = if_else(unit_sales < 0, 0, unit_sales)
  ) %>%
  ungroup

seasonal_naive_preds %>% select(id, unit_sales) %>% write.csv("favorita_seasonal_naive_by_store_item.csv", row.names = F)

```

## Seasonal Naive Promo
```{r}
seasonal_naive_promo <- train %>% 
  mutate(dow = wday(date)) %>% 
  group_by(store_nbr, item_nbr, dow, onpromotion) %>% 
  top_n(n = 1, wt = date) %>%
  select(store_nbr, item_nbr, dow, onpromotion, unit_sales)

fallback_store_item_promo <- seasonal_naive_promo %>% 
  group_by(store_nbr, item_nbr, onpromotion) %>% 
  summarize(store_item_promo_mean = mean(unit_sales, na.rm = TRUE))

fallback_item_promo <- seasonal_naive_promo %>% 
  group_by(item_nbr, onpromotion) %>% 
  summarize(item_promo_mean = mean(unit_sales, na.rm = TRUE))

fallback_item_dow <- seasonal_naive_promo %>% 
  group_by(item_nbr, dow) %>% 
  summarize(item_dow_mean = mean(unit_sales, na.rm = TRUE))

fallback_store_dow <- seasonal_naive_promo %>% 
  group_by(store_nbr, dow) %>% 
  summarize(store_dow_mean = mean(unit_sales, na.rm = TRUE))

seasonal_naive_promo_preds <- test %>% 
  mutate(dow = wday(date)) %>% 
  left_join(seasonal_naive_promo, by = c("store_nbr", "item_nbr", "dow", "onpromotion")) %>% 
  left_join(fallback_store_item_promo, by = c("store_nbr", "item_nbr", "onpromotion")) %>% 
  left_join(fallback_item_promo, by = c("item_nbr", "onpromotion")) %>% 
  left_join(fallback_item_dow, by = c("item_nbr", "dow")) %>%
  left_join(fallback_store_dow, by = c("store_nbr", "dow")) %>%
  mutate(
    unit_sales = if_else(is.na(unit_sales), store_item_promo_mean, unit_sales),
    unit_sales = if_else(is.na(unit_sales), item_promo_mean, unit_sales),
    unit_sales = if_else(is.na(unit_sales), item_dow_mean, unit_sales),
    unit_sales = if_else(is.na(unit_sales), store_dow_mean, unit_sales),
    unit_sales = if_else(unit_sales < 0, 0, unit_sales)
  ) %>%
  ungroup
  
seasonal_naive_promo_preds %>% select(id, unit_sales) %>% write.csv("favorita_seasonal_naive_promo_by_store_item.csv", row.names = F)

```

#Wikipedia
```{r}
train <- fread("~/kaggle/web-traffic-time-series-forecasting/train_2.csv") %>% 
  gather(key = date, value = visits, -Page) %>% 
  mutate(date = ymd(date))


keys <- fread("~/kaggle/web-traffic-time-series-forecasting/key_2.csv") %>% 
  mutate(date = str_sub(Page, -10, -1) %>% ymd,
         Page = str_sub(Page, 1, -12))

test <- fread("~/kaggle/web-traffic-time-series-forecasting/sample_submission_2.csv") %>% 
 left_join(keys, by = "Id") %>% 
  select(-Visits)

```

## Naive

```{r}
naive_w_na <- train %>% filter(date == max(date))
naive_na_pages <- naive_w_na %>% filter(is.na(visits)) %>% pull(Page)
na_last_visits <- train %>%
  filter(Page %in% naive_na_pages) %>% 
  filter(!is.na(visits)) %>% 
  group_by(Page) %>%
  top_n(n = 1, wt = date)

naive_preds <- naive_w_na %>% 
  select(-date) %>% 
  left_join(na_last_visits %>% select(Page, last_visits = visits), by = "Page") %>%
  mutate(visits = if_else(is.na(visits), last_visits, visits),
         visits = if_else(is.na(visits), 0, visits) #zero if non existent in train
         ) %>%
  select(-last_visits)

test %>% 
  left_join(naive_preds, by = "Page") %>% 
  select(Id, Visits = visits) %>% 
  write.csv("wiki_naive_by_page.csv", row.names = F)

```


```{r}
test2
```


# Recruit
```{r}
train <- fread("~/kaggle/recruit-restaurant/train.csv") %>% mutate(date = ymd(date))
test <- fread("~/kaggle/recruit-restaurant/test.csv") %>% mutate(date = ymd(date))

test
```


